In [ ]:
import numpy as np #data manipulation,solved math problem

In [ ]:
lst=list(range(1,25))
print(len(lst))#length of list
#conversion
arr=np.array(lst)
#type
print(type(arr))
print(type(lst))

24
<class 'numpy.ndarray'>
<class 'list'>


In [4]:
#create np arry
arr=np.array([1,2,3,4])
arr #single arr

array([1, 2, 3, 4])

In [ ]:
#arange ()- ussed to create array without range function
arr=np.arange(1,25)
arr #single arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [14]:
# 2d array
arr=np.array([[1,2,3,4],[1,2,3,4]])
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
# null values
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
# 3d array(3 block ,3 rows,3 column)
arr=np.array ([[[1, 2, 3], [4, 5, 6], [4, 5, 6]],[[7, 8, 9], [10, 11, 12], [4, 5, 6]],[[13, 14, 15], [16, 17, 18], [4, 5, 6]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 4,  5,  6]],

       [[13, 14, 15],
        [16, 17, 18],
        [ 4,  5,  6]]])

In [9]:
# one
arr=np.ones((6,10))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# one
arr=np.ones((3,4,5))
arr

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [10]:
#equal space in 1d 
arr=np.linspace(0,10,5)# strt ,end,row
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
#equal space in 2d using reshape(used to covert d to d)
arr=np.linspace(0,10,5).reshape(5,1) #5 row 1 column
arr

array([[ 0. ],
       [ 2.5],
       [ 5. ],
       [ 7.5],
       [10. ]])

In [ ]:
#equal space in 2d using reshape(used to covert d to d)
arr=np.linspace(0,10,5)# strt ,end,row
arr.reshape(5,1) #5 row 1 column

array([[ 0.        ],
       [ 3.33333333],
       [ 6.66666667],
       [10.        ]])

In [58]:
#reshaping 1d to 2d with reshape()
arr=np.arange(1,31)# strt ,end
arr 
arr.reshape(5,6)#row,column

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [59]:
# check shape
arr.shape

(30,)

In [84]:
#in 3d
arr.reshape(3,5,2)
arr

array([[[2, 1],
        [2, 4],
        [4, 4],
        [3, 3],
        [3, 3]],

       [[2, 4],
        [1, 1],
        [1, 3],
        [2, 2],
        [3, 4]],

       [[1, 4],
        [3, 2],
        [3, 1],
        [4, 4],
        [2, 2]]], dtype=int32)

In [85]:
arr.shape

(3, 5, 2)

In [81]:
#random  initilization
arr=np.random.randint(1,31,30)# lower nd upper limit, total no
arr

array([12, 17, 13, 30, 10, 28, 14,  3, 14, 28, 15,  7, 26, 29, 24,  8, 24,
       10,  8, 26, 28, 24, 28,  4,  6, 28, 27,  5,  4,  4], dtype=int32)

In [ ]:
#2d arr
arr=np.random.randint(1,5,(5,6))#lower nd upper limit , row ,column
arr

array([[3, 2, 1, 4, 2, 3],
       [3, 4, 3, 4, 3, 1],
       [1, 3, 4, 4, 2, 4],
       [3, 1, 1, 1, 4, 3],
       [2, 2, 3, 1, 3, 4]], dtype=int32)

In [83]:
#3d arr
arr=np.random.randint(1,5,(3,5,2))#lower nd upper limit ,block, row ,column
arr

array([[[2, 1],
        [2, 4],
        [4, 4],
        [3, 3],
        [3, 3]],

       [[2, 4],
        [1, 1],
        [1, 3],
        [2, 2],
        [3, 4]],

       [[1, 4],
        [3, 2],
        [3, 1],
        [4, 4],
        [2, 2]]], dtype=int32)

In [ ]:
arr=np.random.random(10)# element
#default range 0 to 1
arr

array([0.91005597, 0.60250209, 0.47729762, 0.43582635, 0.70413248,
       0.18912779, 0.29401355, 0.06467458, 0.56553646, 0.73394529])

In [15]:
arr=np.random.randint(10)#range
arr

1

In [17]:
arr=np.random.random(10)# element
#default range 0 to 1
arr

array([0.67937197, 0.36290893, 0.84587667, 0.09097814, 0.75933406,
       0.09674999, 0.41176371, 0.71829645, 0.81409731, 0.41806308])

In [117]:
#d to 2d using random
arr=np.random.random((5,2))
arr

array([[0.62898026, 0.33880035],
       [0.87538074, 0.53150338],
       [0.6887618 , 0.12570425],
       [0.07854516, 0.09160905],
       [0.9498078 , 0.17164617]])

In [118]:
#2d to 3d using random
arr=np.random.random(((5,2,1)))
arr

array([[[0.83691892],
        [0.85520101]],

       [[0.14724363],
        [0.25738353]],

       [[0.96734769],
        [0.81039065]],

       [[0.62271701],
        [0.34882747]],

       [[0.55901817],
        [0.42511864]]])

In [ ]:
arr=np.arange(60).reshape(10,6)
arr
arr.dtype #datatype
arr.shape 
arr.ndim #dimension
arr.size #size

(10, 6)


60

In [127]:
#flatten used to covert 3d or 2d into d
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [129]:
# used to covert 3d or 2d into d
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [131]:
lst=list(range(1,25))
arr=np.array(lst)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [132]:
arr.shape

(24,)

In [ ]:
arr.T.shape# transpose shape

(24,)

In [26]:
lst=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
arr=np.array(lst)
arr


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
arr.shape

(4, 3)

In [28]:
arr.T.shape #transpose

(3, 4)

In [29]:
arr.T #print transpose matrix

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [32]:
arr=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [33]:
arr=arr.reshape((5,12))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [34]:
arr.T

array([[ 0, 12, 24, 36, 48],
       [ 1, 13, 25, 37, 49],
       [ 2, 14, 26, 38, 50],
       [ 3, 15, 27, 39, 51],
       [ 4, 16, 28, 40, 52],
       [ 5, 17, 29, 41, 53],
       [ 6, 18, 30, 42, 54],
       [ 7, 19, 31, 43, 55],
       [ 8, 20, 32, 44, 56],
       [ 9, 21, 33, 45, 57],
       [10, 22, 34, 46, 58],
       [11, 23, 35, 47, 59]])

In [35]:
arr.T.shape

(12, 5)

In [37]:
#access the element of arr
arr=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
#access the element of arr in 1d
arr[2]
arr[10]

np.int64(10)

In [51]:
#accessind multiple values
arr[3:11]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[0:22:2]#strt,end,gap

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [58]:
arr=np.arange(60)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [60]:
arr=arr.reshape((12,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [ ]:
arr[1]#accessing row

array([5, 6, 7, 8, 9])

In [ ]:
arr[1,1]#accesing particualr position

np.int64(6)

In [ ]:
arr[0:5,1:2]#0 to 5 row and 1 column

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [65]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [66]:
arr[11,4]#last element

np.int64(59)

In [ ]:
arr[11][-1]#last element

np.int64(59)

In [ ]:
arr[-1][-1]#last element

np.int64(59)

In [71]:
arr[-1][:4]

array([55, 56, 57, 58])

In [ ]:
arr[:4][-1]#row

array([15, 16, 17, 18, 19])

In [70]:
arr[4,2]=100#replace value
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21, 100,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [72]:
arr=np.arange(225).reshape(5,15,3)
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [73]:
arr.ndim

3

In [ ]:
arr[1]#acesss table

array([[45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89]])

In [ ]:
arr[0][2:7]#row in table

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [ ]:
arr[0][2:7][0]#row nd column in a block

array([6, 7, 8])

In [80]:
arr[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [ ]:
arr[2][3][1]=100000000#chnage value


In [96]:
arr[2][3]

array([       99, 100000000,       101])

In [98]:
arr=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [100]:
arr=arr.reshape((12,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [ ]:
arr +2#add in matrix

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46],
       [47, 48, 49, 50, 51],
       [52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61]])

In [ ]:
arr *2#multi in matrix

array([[  0,   2,   4,   6,   8],
       [ 10,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28],
       [ 30,  32,  34,  36,  38],
       [ 40,  42,  44,  46,  48],
       [ 50,  52,  54,  56,  58],
       [ 60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98],
       [100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118]])

In [ ]:
arr -1#sub in matrix

array([[-1,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58]])

In [ ]:
arr /2 #div in matrix

array([[ 0. ,  0.5,  1. ,  1.5,  2. ],
       [ 2.5,  3. ,  3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ,  6.5,  7. ],
       [ 7.5,  8. ,  8.5,  9. ,  9.5],
       [10. , 10.5, 11. , 11.5, 12. ],
       [12.5, 13. , 13.5, 14. , 14.5],
       [15. , 15.5, 16. , 16.5, 17. ],
       [17.5, 18. , 18.5, 19. , 19.5],
       [20. , 20.5, 21. , 21.5, 22. ],
       [22.5, 23. , 23.5, 24. , 24.5],
       [25. , 25.5, 26. , 26.5, 27. ],
       [27.5, 28. , 28.5, 29. , 29.5]])

In [107]:
arr=arr.reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [110]:
arr1=arr.reshape(12,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [ ]:
arr+arr1#add 2d matrix

array([[  0,   2,   4,   6,   8],
       [ 10,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28],
       [ 30,  32,  34,  36,  38],
       [ 40,  42,  44,  46,  48],
       [ 50,  52,  54,  56,  58],
       [ 60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98],
       [100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118]])

In [116]:
arr=np.arange(1,10)#add 1d matrix
arr1=np.arange(1,10)
arr+arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [117]:
arr*arr1

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [128]:
x=list(range(1,10))#add list
print(x)
y=list(range(11,20))
print(y)
x+y

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[11, 12, 13, 14, 15, 16, 17, 18, 19]


[1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [131]:
x=np.array(x)
y=np.array(y)
x+y

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [132]:
x*y

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171])